baseURL = "https://awsaavedra.com/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Alexander Saavedra"
theme = "hugo-bearblog"

[params]
  # Theme settings
  description = "A simple and concise blog."
  favicon = "favicon.ico"
  showReadingTime = true
  showWordCount = true
  showRssButtonInSectionTermList = true
  showPageNums = true
  showAllPagesInArchive = true
  showBreadCrumbs = true
  showTaxonomies = true

  # Social links
  github = "https://github.com/awsaavedra"
  linkedin = "https://linkedin.com/in/awsaavedra"
  rss = "index.xml"

  # Enable MathJax
  enableMathJax = false

[menu]
  [[menu.main]]
  name = "Documentation"
  url = "/documentation/"
  weight = 1

  [[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

  [[menu.main]]
  name = "Quotes"
  url = "/quotes/"
  weight = 4

  [[menu.main]]
  name = "Resume"
  url = "/resume/"
  weight = 5

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
